### ISSUE TITLE
Python code does not properly calculate size / does not properly handle some devices

### ISSUE THREAD

**Issue by dshadoff** [jamesbowman/spidriver#19]
While trying to identify/read a 8KB FeRAM device MB85RS64V, the JEDEC ID is properly identified (0x04 0x7F 0x03), but the python code then goes into an infinite loop grabbing JEDEC ID again and again instead of determining memory size (which is 64 kbit / 8KB).

Product was purchased here: https://www.adafruit.com/product/1897
Datasheet here: http://www.adafruit.com/datasheets/MB85RS64V-DS501-00015-4v0-E.pdf

Likewise, a 128KB FeRAM MR45V100A was properly identified as (0xae 0x83 0x09), but was improperly identified as 512 bytes (actual size = 1Mbit / 128KB).

**Comment by jamesbowman** [comment]
Fixed the infinite loop bug, and pushed to PyPI:
https://pypi.org/project/spidriver/

You can specify the size on the command-line using the ``-s`` argument, so for the MB85RS64V use ``-s 65536``, and for MR45V100A ``-s 131072``. This is meant for parts where the size isn't computable from the third ID byte, like these.

However reading further down the MB85RS64V datasheet, I see that it uses 16-bit addresses, and the flash tool assumes 24-bit addresses.
![image](https://user-images.githubusercontent.com/894763/60468626-d0908f00-9c8c-11e9-9b44-b1e9d3db891e.png)

However the MR45V100A does use 24-bit addressing, so it might work - please let me know.
![image](https://user-images.githubusercontent.com/894763/60468697-02095a80-9c8d-11e9-8b42-08e33e508c77.png)

**Comment by dshadoff** [comment]
Thanks, the infinite loop bug appears to be fixed.

The third-byte size computation... may not be as straightforward as you had thought.
I tested a AT25SF041 (very common 4Mb / 512KB Flash), which has JEDEC ID (0x1f 0x84 0x01)... this clearly also doesn't follow your expected rules.

As a result, it would be helpful if the spidriver.pdf file could be updated with this point about memory size, including the '-s <size>' operand for the python script.

**Comment by bitshiftnetau** [comment]
Not fixed. Trying to read a [winbond 25Q64/32f](https://www.winbond.com/resource-files/w25q64fv%20revq%2006142016.pdf) and the output "Got JEDEC ID: xx xx xx" outputs on infinite loop. It does get the JEDEC ID.

I have tried connecting the WP and HOLD pins (3 & 5 respectively) to A and B and all 3 combinations of each i.e. WP & HOLD, just WP, just HOLD and nothing seems to work.

I am running:

`python flash.py -h /dev/ttyUSB0`

And have confirmed it does not work when the device and indeed the clip itself are not connected. 

I have an updated version of spidriver installed and I am using the following flash.py example code:

```

#!/usr/bin/env python3

from spidriver import SPIDriver
import struct
import time
import sys
import getopt

def hexdump(s):
    def toprint(c):
        if 32 <= c < 127:
            return chr(c)
        else:
            return "."
    def hexline(s):
        bb = struct.unpack("16B", s)
        return (" ".join(["%02x" % c for c in bb]).ljust(49) +
                "|" + "".join([toprint(c) for c in bb]).ljust(16) + "|")
    return "\n".join([hexline(s[i:i+16]) for i in range(0, len(s), 16)])

if __name__ == '__main__':
    try:
        optlist, args = getopt.getopt(sys.argv[1:], "h:r:w:s:")
    except getopt.GetoptError as reason:
        print()
        print('usage: flash [ -h device ] [ -r file ] [ -w file ] [-s size]')
        print()
        print()
        sys.exit(1)
    optdict = dict(optlist)

    s = SPIDriver(optdict.get('-h', "/dev/ttyUSB0"))
    s.seta(0)
    s.unsel()

    size = int(optdict.get('-s', "0"))

                                # Some primitives for generic flash
    def command(b):
        s.unsel()
        s.sel()
        s.writeread(b)

    def idcode():
        command([0x9f])
        return s.read(3)

    def write_enable():
        command([0x06])

    def status():
        command([0x05])
        (r,) = struct.unpack("B", s.read(1))
        return r

    def wait_ready():
        while True:
            r = status()
            if (r & 1) == 0:
                break

    def addr24(a):
        return [(a >> 16) & 0xff, (a >> 8) & 0xff, a & 0xff]

    def page_program(a, b256):
        # print('page_program', a)
        write_enable()
        command([0x02] + addr24(a))
        s.writeread(b256)
        wait_ready()

    def erase_sector(a):
        # print('erase sector', a)
        write_enable()
        command([0xd8] + addr24(a))
        wait_ready()

    def read(a):
        command([0x03] + addr24(a))

    while True:
        ids = struct.unpack("BBB", idcode())
        print("Got JEDEC ID: %02x %02x %02x" % ids)
        if size > 0:
            break
        if ids[0] not in (0x00, 0xff) and (1 <= ids[2] < 22):
            break
    if size == 0:
        size = 1 << ids[2]
    print("Flash size is %d bytes" % size)

    print("Status is %02x" % status())

    if '-r' in optdict:
        read(0)
        chunk = 8 * 1024
        size,chunk = 128,128
        with open(optdict['-r'], "wb") as f:
            for a in range(0, size, chunk):
                d = s.read(chunk)
                print(d)
                f.write(d)
                print("%d/%d KBytes" % (a / 1024, size / 1024))
    if '-w' in optdict:
        write_enable()
        command([0xc7])
        wait_ready()
        with open(optdict['-w'], "rb") as f:
            for a in range(0, size, 256):
                d = f.read(256)
                if len(d) == 0:
                    break
                page_program(a, d)
                print("%d/%d KBytes" % (a / 1024, size / 1024))
    write_enable()

    s.unsel()
    s.seta(1)
    s.detach()

```

**Comment by biboc** [comment]
Agree with @dshadoff , size calculation does not work as expected for my m25p20 memory
https://media-www.micron.com/-/media/client/global/documents/products/data-sheet/nor-flash/serial-nor/m25p/m25p20.pdf?rev=3166183bc4514b9999c9c2fc7956ecca
